Algoritmo "testedeentrada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2024
Var
// Seção de Declarações das variáveis 
   x, y, z, a, b, c, d : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   x <- 2.0
   y <- 3.0
   z <- -7.0
   
   a <- Exp(x,y)
   escreval(a)

Fimalgoritmo