Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2024
Var
// Seção de Declarações das variáveis 

  a: real
  b: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   a <- 5.0
   b <- Int(a)

   
   escreval(b)
Fimalgoritmo